name: NPM Auto Deprecate

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  auto-deprecate:
    name: NPM Auto Deprecate
    runs-on: ubuntu-latest
    if: github.repository_owner == 'Rygent'
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: Use pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          registry-url: https://registry.npmjs.org/
      - name: Deprecate versions
        run: pnpm dlx @favware/npm-deprecate@latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
