name: Continuous Integration

on:
  push:
    branches: ['main']
  pull_request:

jobs:
  Linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: Use Node.js v18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn
          registry-url: https://registry.yarnpkg.org/
      - name: Install Dependencies
        run: yarn --immutable
      - name: Run ESLint
        run: yarn lint --fix=false

  Testing:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: Use Node.js v18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn
          registry-url: https://registry.yarnpkg.org/
      - name: Install Dependencies
        run: yarn --immutable
      - name: Build test dependencies
        run: yarn turbo run build
      - name: Run tests
        run: |
          curl -L ${ENV_FILE_URL} -o .env

          yarn test
        env:
          ENV_FILE_URL: ${{ secrets.ENV_FILE_URL }}

  Building:
    name: Compile source code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: Use Node.js v18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn
          registry-url: https://registry.yarnpkg.org/
      - name: Install Dependencies
        run: yarn --immutable
      - name: Compile Projects
        run: yarn build
