name: Continuous Delivery

on:
  workflow_dispatch:
    inputs:
      repository:
        description: The {owner}/{repository} that is being deployed.
        required: false
        default: Rygent/Utilities
      packages:
        description: The {package} that is being published.
        required: false

jobs:
  Publish:
    name: Publish Next to npm
    runs-on: ubuntu-latest
    if: github.repository_owner == 'Rygent'
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: ${{ github.event.inputs.repository || 'Rygent/Utilities' }}
      - name: Use Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          registry-url: https://registry.yarnpkg.com/
      - name: Install Dependencies
        run: yarn --immutable
      - name: Build all packages
        run: yarn build
      - name: Bump Versions & Publish
        run: |
          # Resolve the tag to be used. "next" for schedule & dispatch events.
          TAG=$(echo 'next')

          yarn config set npmAuthToken ${NODE_AUTH_TOKEN}
          yarn config set npmPublishRegistry "https://registry.yarnpkg.com"

          for d in packages/${{ github.event.inputs.packages || '*' }}; do
            pushd $d
            yarn bump --preid "${TAG}.$(git rev-parse --verify --short HEAD)"
            yarn npm publish --tag ${TAG} || true
            popd
          done
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
