name: Continuous Delivery

on:
  workflow_dispatch:
    inputs:
      repository:
        description: The {owner}/{repository} that is being deployed.
        required: false
        default: Rygent/Utilities

jobs:
  Publish:
    name: Publish Next to npm
    runs-on: ubuntu-latest
    if: github.repository_owner == 'Rygent'
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: ${{ github.event.inputs.repository || 'Rygent/Utilities' }}
      - name: Use pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          registry-url: https://registry.npmjs.org/
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile --prefer-offline
      - name: Build all packages
        run: pnpm run build
      - name: Bump Versions & Publish
        run: |
          # Resolve the tag to be used. "next" for schedule & dispatch events.
          TAG=$(echo 'next')

          for d in packages/*; do
            pushd $d
            pnpm run bump --preid "${TAG}.$(git rev-parse --verify --short HEAD)"
            pnpm publish --tag ${TAG} || true
            popd
          done
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
