name: Continuous Integration

on:
  push:
    branches: ['main']
  pull_request:

jobs:
  Linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: Use pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile --prefer-offline
      - name: Run ESLint
        run: pnpm run lint --fix=false

  Testing:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: Use pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile --prefer-offline
      - name: Build test dependencies
        run: pnpm exec turbo run build
      - name: Run tests
        run: |
          curl -L ${ENV_FILE_URL} -o .env

          pnpm run test
        env:
          ENV_FILE_URL: ${{ secrets.ENV_FILE_URL }}

  Building:
    name: Compile source code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: Use pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile --prefer-offline
      - name: Compile Projects
        run: pnpm run build
