name: PR Labeler

on:
  pull_request_target:

jobs:
  pr-triage:
    name: PR Triage
    runs-on: ubuntu-latest
    steps:
      - name: Automatically label PR
        uses: actions/labeler@v6
        with:
          configuration-path: .github/pr-labeler.yml
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          sync-labels: true
